# trust_module/rho_adaptor.py

import numpy as np
from scipy.stats import spearmanr
from typing import Tuple

class RhoWeightAdaptor:
    def __init__(self, initial_theta: np.ndarray, eta: float):
        self.previous_theta = initial_theta
        self.eta = eta

    def update_weights(self, cosine_scores: np.ndarray, 
                       entropy_scores: np.ndarray, 
                       reputation_scores: np.ndarray, 
                       delta_acc: float) -> Tuple[float, float, float]:
        # Compute Spearman correlation
        rho, _ = spearmanr([cosine_scores, entropy_scores, reputation_scores], axis=1)
        
        # Update theta using softplus
        theta = np.exp(self.previous_theta + self.eta * rho)
        theta /= theta.sum()  # Normalize to ensure α + β + γ = 1
        
        # Update previous_theta for the next round
        self.previous_theta = theta
        
        return tuple(theta)