# @package _global_
# Cosine similarity trust evaluation configuration

trust:
  name: cosine
  mode: cosine
  threshold: 0.6
  
  # Cosine similarity parameters
  parameters:
    cosine:
      min_similarity: 0.0
      max_similarity: 1.0
      normalize_updates: true
      
  # Trust update settings
  update:
    frequency: 1  # Update every round
    smoothing_factor: 0.05
    
  # Trust-based client selection
  selection:
    enabled: true
    min_trust_score: 0.4
    max_malicious_ratio: 0.1
