# @package _global_
# Hydra configuration for TRUST-MCNet federated learning framework
# This file defines the default configuration composition

defaults:
  - dataset: iot_general
  - env: local
  - strategy: fedavg
  - trust: hybrid
  - model: mlp
  - training: default
  - ray: local
  - _self_

# Hydra configuration for experiment management
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: false

# Federated learning configuration
federated:
  num_rounds: 5
  fraction_fit: 0.8
  fraction_evaluate: 0.2
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

# Simulation configuration
simulation:
  use_legacy: false  # Use enhanced simulation by default (true for legacy)
  use_enhanced_client: true
  enable_trust_evaluation: true
  trust_threshold: 0.5
  enable_metrics_aggregation: true

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_to_file: false
  log_file: null
  
  # Metrics logging
  metrics:
    enable_tensorboard: false
    tensorboard_dir: "logs/tensorboard"
    log_frequency: 1  # Log every N rounds
