# TRUST MCNet Configuration File

# Model Configuration
model:
  type: "MLP"  # Options: "MLP", "LSTM"
  mlp:
    input_dim: 784  # 28*28 for MNIST images
    hidden_dims: [256, 128, 64]
    output_dim: 2  # Binary classification (normal vs anomaly)
  lstm:
    input_dim: 784
    hidden_dim: 128
    num_layers: 2
    output_dim: 2

# Client Configuration
client:
  learning_rate: 0.001
  batch_size: 32
  local_epochs: 5
  optimizer: "Adam"  # Options: "Adam", "SGD", "RMSprop"

# Federated Learning Configuration
federated:
  num_clients: 5
  num_rounds: 3
  fraction_fit: 0.8  # Fraction of clients to train each round
  fraction_evaluate: 0.2  # Fraction of clients to evaluate each round
  min_fit_clients: 5
  min_evaluate_clients: 2
  min_available_clients: 5
  
  # Flwr-specific configuration
  strategy: "FedAdam"
  strategy_config:
    eta: 0.001  # Server-side learning rate for FedAdam
    eta_l: 0.001  # Client-side learning rate
    beta_1: 0.9  # Momentum parameter
    beta_2: 0.999  # Second moment parameter
    tau: 0.001  # Control variates parameter
    
  # IoT device considerations
  iot_config:
    max_memory_mb: 512  # Maximum memory usage per client
    max_cpu_percent: 70  # Maximum CPU usage per client
    connection_timeout: 30  # Connection timeout in seconds
    resource_monitoring: true
    adaptive_batch_size: true
    min_batch_size: 8
    max_batch_size: 64

# Trust Mechanism Configuration
trust:
  enabled: true
  trust_threshold: 0.7
  trust_decay_factor: 0.95
  reputation_weight: 0.3

# Data Configuration
data:
  # Dataset selection
  dataset_type: "mnist"  # Options: "mnist", "synthetic", "csv"
  data_dir: "data/MNIST"  # Directory for MNIST data
  download: true  # Auto-download MNIST if not present
  
  # MNIST specific configuration
  anomaly_digits: [1, 7]  # Digits to treat as anomalies for binary classification
  
  # General data configuration
  target_column: "label"
  feature_columns: []  # Empty list means all columns except target
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  normalize: true
  handle_missing: "mean"  # Options: "mean", "median", "drop"
  num_workers: 0  # Data loader workers (0 for IoT devices)
  
  # Simulation-specific parameters
  dataset_size: 5000  # Total samples for synthetic data
  anomaly_ratio: 0.1  # Ratio of anomalous samples
  distribution: "iid"  # Options: "iid", "non_iid"

# Training Configuration
training:
  device: "auto"  # Options: "auto", "cpu", "cuda"
  seed: 42
  epochs: 5  # For centralized baseline training
  early_stopping: true
  patience: 10
  save_checkpoints: true
  checkpoint_dir: "checkpoints"

# Logging Configuration
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  log_file: "training.log"
  log_metrics: true
  log_frequency: 10  # Log every N rounds

# Evaluation Metrics
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"
  - "auc"

# Anomaly Detection Specific
anomaly_detection:
  threshold: 0.5
  contamination: 0.1  # Expected fraction of anomalies
  method: "classification"  # Options: "classification", "reconstruction"

# Experiment Configuration
experiment:
  name: "trust_mcnet_mnist_baseline"
  description: "MNIST anomaly detection with random weight aggregation"
  baseline_mode: true  # Use random weights instead of trust scores
  save_results: true
  results_dir: "results"
  
  # Logging and visualization
  log_level: "INFO"
  save_plots: true
  plot_format: "png"
  
  # Metrics to track
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "detection_rate"
  
  # Explainability
  shap_analysis: true
  shap_samples: 100  # Number of samples for SHAP analysis
