# @package _global_
# Hydra configuration for TRUST-MCNet federated learning framework
# This file defines the default configuration composition

defaults:
  - dataset: mnist
  - env: local
  - strategy: fedavg
  - trust: hybrid
  - model: mlp
  - _self_

# Hydra configuration for experiment management
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: false

# Training configuration
training:
  epochs: 1
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: adam

# Federated learning configuration
federated:
  num_rounds: 3
  fraction_fit: 0.8
  fraction_evaluate: 0.2
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
